import { Component, Inject } from "@angular/core";
import { MAT_SNACK_BAR_DATA } from "@angular/material/snack-bar";

@Component({
  selector: './rolls-snack-bar-component',
  template: `<span>{{ data?.message }}</span> <mat-icon matTooltip={{data?.result1}} matTooltipPosition="above" style="color:{{data?.color1}}">{{ data?.icon1 }}</mat-icon><mat-icon matTooltip={{data?.result2}} matTooltipPosition="above" style="color:{{data?.color2}};">{{ data?.icon2 }}</mat-icon><mat-icon matTooltip={{data?.result3}} matTooltipPosition="above" style="color:{{data?.color3}};">{{ data?.icon3 }}</mat-icon><mat-icon matTooltip={{data?.result4}} matTooltipPosition="above" style="color:{{data?.color4}};">{{ data?.icon4 }}</mat-icon><mat-icon matTooltip={{data?.result5}} matTooltipPosition="above" style="color:{{data?.color5}};">{{ data?.icon5 }}</mat-icon><mat-icon matTooltip={{data?.result6}} matTooltipPosition="above" style="color:{{data?.color6}};">{{ data?.icon6 }}</mat-icon><mat-icon matTooltip={{data?.result7}} matTooltipPosition="above" style="color:{{data?.color7}};">{{ data?.icon7 }}</mat-icon><mat-icon matTooltip={{data?.result8}} matTooltipPosition="above" style="color:{{data?.color8}};">{{ data?.icon8 }}</mat-icon><mat-icon matTooltip={{data?.result9}} matTooltipPosition="above" style="color:{{data?.color9}};">{{ data?.icon9 }}</mat-icon><mat-icon matTooltip={{data?.result10}} matTooltipPosition="above" style="color:{{data?.color10}};">{{ data?.icon10 }}</mat-icon><mat-icon matTooltip={{data?.result11}} matTooltipPosition="above" style="color:{{data?.color11}};">{{ data?.icon11 }}</mat-icon><mat-icon matTooltip={{data?.result12}} matTooltipPosition="above" style="color:{{data?.color12}};">{{ data?.icon12 }}</mat-icon><mat-icon matTooltip={{data?.result13}} matTooltipPosition="above" style="color:{{data?.color13}};">{{ data?.icon13 }}</mat-icon><mat-icon matTooltip={{data?.result14}} matTooltipPosition="above" style="color:{{data?.color14}};">{{ data?.icon14 }}</mat-icon><mat-icon matTooltip={{data?.result15}} matTooltipPosition="above" style="color:{{data?.color15}};">{{ data?.icon15 }}</mat-icon><mat-icon matTooltip={{data?.result16}} matTooltipPosition="above" style="color:{{data?.color16}};">{{ data?.icon16 }}</mat-icon> <div>{{ data?.message2 }}</div> <div>{{ data?.complication }}`,
  styleUrls: ['./rolls-snack-bar.component.css'],
})
export class RollsSnackBarComponent {
  constructor(@Inject(MAT_SNACK_BAR_DATA) public data: any) {}
}